baseurl = "https://HataKyoka4242.github.io/my.portfolio"
title = "My Portfolio Site"
theme = "hugo-creative-portfolio-theme"
languageCode = "ja"
publishDir = "docs"
canonifyurls = true
tag = "tags"
contentDir = "post"
disableKinds = ["RSS", "sitemap"]
disqusShortname = "your-disqus-short-name"
